### ISSUE TITLE
Testing, demo dataset, action workflow 

### ISSUE THREAD

**Issue by FlynnOConnell** [MillerBrainObservatory/LBM-CaImAn-MATLAB#21]
## Issue

To avoid breaking changes making it into future releases, we should incorporate a test-suite using sub-sampled ground-truth dataset with a reliable output. 

The `high-resolution` dataset fits the mold - tied for our smallest dataset and the smallest resolution helps increase contrast to evaluate phase correction and pixel trimming results.

## TO-DO:
- [ ] Create demo dataset with original planes interleaved and original metadata remaining intact
- [ ] Confirm reliable output metrics such as:
    - [ ] input image dimensions
    - [ ] output image dimensions
    - [ ] calculated planar-scan phase
    - [ ] average per-roi planar scan phase
    - [ ] total number of pixels / plane in final movie
- [ ] Automate tests on each pull request for review
